package com.savingcoach.app.navigation

sealed class Routes(val route: String) {
    object Auth : Routes("auth")
    object Dashboard : Routes("dashboard")
    object Expenses : Routes("expenses")
    object Challenges : Routes("challenges")
    object Investment : Routes("investment")
    object AddExpense : Routes("add_expense")
    object Chat : Routes("chat")
    object Camera : Routes("camera")
    object Budget : Routes("budget")
    object Settings : Routes("settings")
    object CalendarHistory : Routes("calendar_history")
    object Notifications : Routes("notifications")
    object EditUsername : Routes("edit_username")
    object OnboardingAge : Routes("onboarding_age")
    object OnboardingGender : Routes("onboarding_gender")
    object OnboardingSalary : Routes("onboarding_salary")
    object EditEmail : Routes("edit_email")
    object EditAge : Routes("edit_age")
    object EditGender : Routes("edit_gender")
    object EditSalary : Routes("edit_salary")
    object OnboardingFieldOfWork : Routes("onboarding_field_of_work")
    object EditFieldOfWork : Routes("edit_field_of_work")
    object ForgotPassword : Routes("forgot_password")
    object ChangePassword : Routes("change_password")
    object ExportData : Routes("export_data")
    object EditCurrency : Routes("edit_currency")
    object EditLanguage : Routes("edit_language")
}

